package lo54.projetlo54.core.entity;
// Generated 15 mai 2016 21:15:59 by Hibernate Tools 4.3.1



/**
 * Client generated by hbm2java
 * @author Jordan 
 */
public class Client  implements java.io.Serializable {


     private Integer idClient;
     private CourseSession courseSession;
     private String lastname;
     private String firstname;
     private String address;
     private String phone;
     private String email;

    public Client() {
    }
	
    public Client(String lastname, String firstname, String address, String phone) {
        this.lastname = lastname;
        this.firstname = firstname;
        this.address = address;
        this.phone = phone;
    }
    public Client(CourseSession courseSession, String lastname, String firstname, String address, String phone, String email) {
       this.courseSession = courseSession;
       this.lastname = lastname;
       this.firstname = firstname;
       this.address = address;
       this.phone = phone;
       this.email = email;
    }
   
    public Integer getIdClient() {
        return this.idClient;
    }
    
    public void setIdClient(Integer idClient) {
        this.idClient = idClient;
    }
    public CourseSession getCourseSession() {
        return this.courseSession;
    }
    
    public void setCourseSession(CourseSession courseSession) {
        this.courseSession = courseSession;
    }
    public String getLastname() {
        return this.lastname;
    }
    
    public void setLastname(String lastname) {
        this.lastname = lastname;
    }
    public String getFirstname() {
        return this.firstname;
    }
    
    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Override
    public String toString() {
        return "Client{" + "idClient=" + idClient + ", lastname=" + lastname + ", firstname=" + firstname + ", address=" + address + ", phone=" + phone + ", email=" + email + ", courseSession=" + courseSession.getIdCourseSession() + '}';
    }

}


