package lo54.projetlo54.core.entity;
// Generated 15 mai 2016 21:15:59 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Location generated by hbm2java
 * @author Jordan 
 */
public class Location  implements java.io.Serializable {


     private Integer idLocation;
     private String city;
     private Set courseSessions = new HashSet(0);

    public Location() {
    }

	
    public Location(String city) {
        this.city = city;
    }
    public Location(String city, Set courseSessions) {
       this.city = city;
       this.courseSessions = courseSessions;
    }
   
    public Integer getIdLocation() {
        return this.idLocation;
    }
    
    public void setIdLocation(Integer idLocation) {
        this.idLocation = idLocation;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Set getCourseSessions() {
        return this.courseSessions;
    }
    
    public void setCourseSessions(Set courseSessions) {
        this.courseSessions = courseSessions;
    }




}


